version: '3'
services:
    # database:
    #     image: mysql:8
    #     container_name: db_stella
    #     restart: unless-stopped
    #     ports:
    #         - 33061:3306
    #     environment:
    #         - MYSQL_ROOT_PASSWORD=password
    #         - MYSQL_ROOT_HOST=%
    #     volumes:
    #         - ./bin/mysql:/var/lib/mysql
    webserver:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - '33060:80'
            - '33062:443'
        volumes:
            - ./webserver:/usr/share/nginx/html
    # backend:
    #     build:
    #         context: ./backend
    #         dockerfile: ./Dockerfile
    #     ports:
    #         - '33063:30000'
    #     restart: unless-stopped
    #     depends_on:
    #         - database
    #     environment:
    #         - DATABASE_HOST=db_stella
    #         - DATABASE_PORT=3306
    #         - DATABASE_USERNAME=root
    #         - DATABASE_PASSWORD=password
